### ISSUE TITLE
Could you release the complete evaluation code?

### ISSUE THREAD

**Issue by DoubleBite** [ai-systems/unification_reconstruction_explanations#1]
Hi,

I really appreciate your work and tryna reproduce it now.
Could you provide the complete evaluation code that can produce a performance breakdown as that in Table 2?

**Comment by mValentino91** [comment]
Hi,

Thank you very much for your interest and sorry for the late reply! We are going to release the code for the breakdown evaluation soon after the EACL conference! 

Meanwhile, if you need to reproduce this type of evaluation you can do it by using the shared task 2019 data available at the following URL: http://cognitiveai.org/dist/worldtree_corpus_textgraphs2019sharedtask_withgraphvis.zip 

In order to do that, you would need to modify the evaluation script "evaluate.py" by considering only the facts belonging to a specific category. The explanatory roles in table 2.a can be found for each fact in the annotation of the gold explanations in the original dataset. Regarding table 2.b, we compute the number of lexical overlaps between questions and facts without considering the stopwords. For table 2.c, you can find the corresponding mapping between tables and inference types in the original data at the following path: "annotation/expl-tablestore-export-2017-08-25-230344/tableKnowledgeCategories.tsv"

Please let us know if you have any additional questions!
